### ISSUE TITLE
[bug]文章编辑页右上角的发布键莫名消失，完全发不了blog了

### ISSUE THREAD

**Issue by RECACV** [Crossbell-Box/xLog#1020]
![1CA4E1BD-4BC7-4DA2-B72A-EF530B8C66E7](https://github.com/Crossbell-Box/xLog/assets/118593676/e1cc93b1-6a3d-4e3e-adb1-693a8fff943a)
退出重登也没用，不知道怎么回事，不管是新建文章还是编辑旧文都无法发布

**Comment by xtmu** [comment]
2023-10-09 12:01:26 UTC 服务器已经挂了

**Comment by DIYgod** [comment]
I can't reproduce it. Have you installed any strange ad-blocking plugins?

**Comment by RECACV** [comment]
> I can't reproduce it. Have you installed any strange ad-blocking plugins?

是ipad自带的safari，没有安装任何浏览器插件

**Comment by DIYgod** [comment]
> > I can't reproduce it. Have you installed any strange ad-blocking plugins?
> 
> 是ipad自带的safari，没有安装任何浏览器插件 @DIYgod

我用 iPad 依然无法复现这个问题，你的系统版本是多少

![IMG_0760](https://github.com/Crossbell-Box/xLog/assets/8266075/f4aa6470-6437-4e5d-85ab-032b3cfdb14f)

**Comment by RECACV** [comment]
> > > I can't reproduce it. Have you installed any strange ad-blocking plugins?
> > 
> > 
> > 是ipad自带的safari，没有安装任何浏览器插件 @DIYgod
> 
> 我用 iPad 依然无法复现这个问题，你的系统版本是多少
> 
> ![IMG_0760](https://user-images.githubusercontent.com/8266075/274622539-f4aa6470-6437-4e5d-85ab-032b3cfdb14f.PNG)

16.1.1
另外我还试着下了edge，Chrome，注册新号，但都没有发布键
一周前发布键是有的，当时我正在编辑一篇文章，准备发布的时候就莫名其妙突然消失了
