### ISSUE TITLE
估低的中文 `readingTime` 计算（Underestimated `readingTime` for Chinese）

### ISSUE THREAD

**Issue by Songkeys** [Crossbell-Box/xLog#1021]
因为觉得中文阅读速度的计算问题更大， 所以我就用中文提问了。

现在预估量是 300 字每分钟：

https://github.com/Crossbell-Box/xLog/blob/e6994af0e1b8de0ed4dcbeb49eff0b3404ad5fb2/src/lib/reading-time.ts#L1-L12

但这个速度显然是太低了。我看到 [2002年颁布的「全日制普通高级中学语文教学大纲」规定，中国高中生阅读一般现代文的速度不少于 600字/分钟。](https://www.zhihu.com/market/paid_column/1269639105593556992/section/1269647252945432576)

![2002年颁布的「全日制普通高级中学语文教学大纲」规定，中国高中生阅读一般现代文的速度不少于 600字/分钟。](https://github.com/Crossbell-Box/xLog/assets/22665058/5f0cb18e-8f75-4fbc-b087-bb753fd66604)

实际浏览体验中，也能明显感到这个问题。比如这篇文章[《成为小红书博主的 Day14》](https://xlog.app/post/atlas/xhs-day14)，我的速览时间大概只有不到二十秒，细读的话也不会超过一分钟。但目前网页上显示的预估时间是 2 分钟。

![成为小红书博主的 Day14](https://github.com/Crossbell-Box/xLog/assets/22665058/7fdfe1d8-fe39-4dc9-a981-e593d573fb61)

我觉得将速度提到 600 字每分钟会比较合理。

另外我相信大家网上冲浪和看书阅读还是有区别的，一般都是速览，感兴趣或者内容深奥才会慢读精读，可能为了精准再乘上一个速读倍率大概 1.5~2 会更合理？（不过也没必要矫枉过正。）

---

P.S. 另附英文阅读速度研究 [Average Reading Speed (WPM) by Age and Grade Level](https://scholarwithin.com/average-reading-speed)。目前 300 wpm 似乎是比较合理的。（但同上，网上冲浪的阅读速度可能更快。）

![Grade Level and Age / Words-Per-Minute](https://github.com/Crossbell-Box/xLog/assets/22665058/e18beed5-9eb8-42db-8cef-db8f3d6c653c)

**Comment by DIYgod** [comment]
看知乎讨论似乎不同人和不同内容区别还是挺大的 https://www.zhihu.com/question/20327487 ，但我自己也感觉确实这个预估太长了，所以中文预估速度已修改为 600 字每分钟 3f4ed416e9d31637e0dde67a045dd4a9188e3c6e
