### ISSUE TITLE
【样式问题】Dark Mode 下，GitHub 的 icon 似乎太黑了？都快看不见了（

### ISSUE THREAD

**Issue by vikiboss** [Crossbell-Box/xLog#1023]
如下图所示：

<img width="672" alt="image" src="https://github.com/Crossbell-Box/xLog/assets/53367348/39659f55-e6a5-41c7-af6b-b4b47c6d8c7c">

看看是不是需要考虑动态变更 `icon`，或者使用添加边框等其他可以突出显示的方式 🤔️？

**Comment by DIYgod** [comment]
This issue is caused by image compression, it has been fixed in b971a69519e793e4b353f7a445add3d46ef55d20
