### ISSUE TITLE
无法创建账户

### ISSUE THREAD

**Issue by maajiko** [Crossbell-Box/xLog#1027]
![Screenshot_2023-10-22-17-28-18-979_com.microsoft.emmx.jpg](https://github.com/Crossbell-Box/xLog/assets/83452696/c89c2c53-50c3-480a-9ccc-a859cd97d1ed)

这种是什么问题，我切换其他网络也不行，第1次用，我也不太懂🥺

**Comment by DIYgod** [comment]
看起来是钱包的问题，请问你用的是什么钱包

**Comment by maajiko** [comment]
> 看起来是钱包的问题，请问你用的是什么钱包

用的是欧易的 Web 钱包，那有没有其他钱包推荐，用小狐狸吗

**Comment by DIYgod** [comment]
小狐狸是最推荐的，有些钱包只允许少数固定的几个链，无法用于 xLog 所使用的 Crossbell 链

**Comment by JIeJaitt** [comment]
> 小狐狸是最推荐的，有些钱包只允许少数固定的几个链，无法用于 xLog 所使用的 Crossbell 链

请问有注册教程嘛？第一次接触区块链感觉太抽象了
