### ISSUE TITLE
功能建议：请问文章可以不强制需要头图嘛？

### ISSUE THREAD

**Issue by JIeJaitt** [Crossbell-Box/xLog#1028]
简洁党觉得文章头图没必要而且为每篇文章配图是一件选择恐惧症的事情，希望支持自己可选是否为文章配图

**Comment by DIYgod** [comment]
现在还没有这个功能，但不用担心，它有默认开启的 AI 过滤，也不用担心污染，真追求高质量的用户会看首页的精选的，最新就是什么样的内容都会有，很正常，别紧张

**Comment by JIeJaitt** [comment]
> 现在还没有这个功能，但不用担心，它有默认开启的 AI 过滤，也不用担心污染，真追求高质量的用户会看首页的精选的，最新就是什么样的内容都会有，很正常，别紧张

哦哦哦好的
