### ISSUE TITLE
[功能请求]Latex语法支持不完善

### ISSUE THREAD

**Issue by liuke101** [Crossbell-Box/xLog#1031]
目前仅支持：$$ function $$
希望$ function $ 行中公式希望得到支持，方便我做迁移

**Comment by DIYgod** [comment]
我们曾经支持过，但是发现误判太多了，任何 $ 都会被识别成公式，所以只能去掉

**Comment by liuke101** [comment]
> 我们曾经支持过，但是发现误判太多了，任何 $ 都会被识别成公式，所以只能去掉

好吧😢
