### ISSUE TITLE
链接预览封面的优化建议

### ISSUE THREAD

**Issue by devyujie** [Crossbell-Box/xLog#1038]
在推特或者其他平台发博客链接，会出现预览封面，现在好像是索引的最后一张文章配图，**建议改成发文章时上传的封面图**，没有上传封面图的可以选择索引第一张，因为有的人会专门设计好看的封面图。

![image](https://github.com/Crossbell-Box/xLog/assets/48620527/a34085d0-1dd2-4686-982a-fa335005da2b)

**Comment by DIYgod** [comment]
xLog will output all images as metadata. The reason for this issue is that Twitter will use the last image as the cover, I have reversed here 55db2992b7bfbd456e381a628ae635007d39013f
