### ISSUE TITLE
`external_urls` in note `meta` is 404 url

### ISSUE THREAD

**Issue by Innei** [Crossbell-Box/xLog#1080]
![CleanShot 2023-11-28 at 11  00 57@2x](https://github.com/Crossbell-Box/xLog/assets/41265413/927af207-1621-4d3f-82f3-95a0ebd13777)

Such as this: https://innei-4525.xlog.app/posts/note-159. But 404.

The right URL is https://innei-4525.xlog.app/note-159

The request info:

```
curl 'https://indexer.crossbell.io/v1/characters/52055/notes/427' \
  -H 'authority: indexer.crossbell.io' \
  -H 'accept: */*' \
  -H 'accept-language: zh-CN,zh;q=0.9,en;q=0.8,und;q=0.7' \
  -H 'dnt: 1' \
  -H 'origin: https://blog.innei.ren' \
  -H 'referer: https://blog.innei.ren/' \
  -H 'sec-ch-ua: "Google Chrome";v="119", "Chromium";v="119", "Not?A_Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36' \
  --compressed
```

**Comment by DIYgod** [comment]
I am unable to replicate this field on other blogs. In theory, this field is uploaded when publishing a post, but xLog no longer includes this field in its uploads. Could you please check if you included this field when synchronizing the post?

**Comment by Innei** [comment]
@DIYgod I use `unidata.js` to set a new note, maybe it is the `unidata.js` problem?

**Comment by Innei** [comment]
I took a look at the implementation method of xLog for `creatPage`.

But `usePostNote` is imported from `@crossbell/connect-kit`, this is a React-only library, and can not used in pure Vue. I did not want to bundle React runtime in my project.

![CleanShot 2023-12-15 at 2  57 45@2x](https://github.com/Crossbell-Box/xLog/assets/41265413/ff01f88f-5daf-4bfb-9655-ed00c447f0cc)

**Comment by DIYgod** [comment]
This field is passed in Unidata through `related_urls`, have you used this field?

The recommended approach now is to use [crossbell.js](https://crossbell.js.org/), regardless of what framework you are using.
