### ISSUE TITLE
I can't find the contract source code.

### ISSUE THREAD

**Issue by yuankunyong** [Crossbell-Box/xLog#1124]
Excuse me，could somebody tell me how can I get the contract source code? I just want to learn from it.

**Comment by DIYgod** [comment]
Here are some documents and contract addresses: https://github.com/Crossbell-Box/Crossbell-Contracts/wiki

According to the contract address, you can find the code, for example: https://scan.crossbell.io/address/0x4dd1ed784b0C2bdF58a16e6311ad8E3f533401e8/contracts#address-tabs
