### ISSUE TITLE
xLog for iOS用钱包登录不了。

### ISSUE THREAD

**Issue by Faron-Pan** [Crossbell-Box/xLog#1217]
xLog for iOS用钱包登录不了，点击“连接钱包”没有反应，特殊网络也没用。但是点“邮箱登录”可以正常用。另外，浏览内容也不稳定，缩略图可以加载，但是有部分内容正文点进去就提示“网络错误”。

**Comment by enpitsuLin** [comment]
目测是网络不稳定导致没有成功和 wc 服务器连接，国内用户这一环就是会有点问题，科学上网是付费的吧？走的全局模式吗？试过其他节点没有？

**Comment by Faron-Pan** [comment]
问题已解决。直连重新试了几遍就可以了。感谢！
