### ISSUE TITLE
Feature Request: Full support for custom post path

### ISSUE THREAD

**Issue by ahonn** [Crossbell-Box/xLog#128]
I want to migrate my blog to xlog, but it seems that custom path for blog posts is not supported.
For example, I want the post URL to be `/blog/xxxxx` after publish, but it doesn't seem to work after setting it on the post page, the post URL after publish is `%2Fblog%2Fxxxxx`.

**Comment by DIYgod** [comment]
This will cause problems for the routing, so it cannot be implemented for now. 
And we have disallowed the use of escaped characters in slugs
