### ISSUE TITLE
RSS Support

### ISSUE THREAD

**Issue by Songkeys** [Crossbell-Box/xlog#13]
An RSS link for each xlog site.

**Comment by DIYgod** [comment]
Done. 525af6fa03ed7deb3bc5922708accb5f18b7e379

Like https://song.xlog.app/feed

**Comment by ilihu** [comment]
json feed!
Don't plan to support rss feed?

**Comment by DIYgod** [comment]
@ilihu  I think JSON Feed is a better format for the 21st century, is there any reason you need RSS?
