### ISSUE TITLE
需求：给页面增加单独定制 CSS 的能力

### ISSUE THREAD

**Issue by devyujie** [Crossbell-Box/xLog#1332]
虽然在设置里提供了自定义 CSS 的地方，但好像都是通用的，就代表着也会应用在 `页面` 之中，在前端显示形式上，`页面` 和已发布的文章样式一样，[例如](https://realyujie.xlog.app/about)我想把这个页面的点赞功能和底部的评论等都隐藏掉，但没法在自定义 CSS 中设置，这样会影响文章样式。

**能否在 `页面` 编辑的侧边栏中，增加一块区域用于自定义这部分的 CSS**，以扩大 `页面` 的可编辑范围和显示能力。

![image](https://github.com/Crossbell-Box/xLog/assets/48620527/d7eaa9ac-209d-4c91-89cc-00ef47f73683)

**Comment by DIYgod** [comment]
xLog supports writing CSS directly in posts.

```html
<style>
 // your css
</style>
```

**Comment by devyujie** [comment]
> xLog supports writing CSS directly in posts.
> 
> ```
> <style>
>  // your css
> </style>
> ```

感谢！用上啦~
