### ISSUE TITLE
<img>tag will make page unaccessiable.

### ISSUE THREAD

**Issue by Muffeter** [Crossbell-Box/xLog#135]
When you add a <img> tag in the post editor, this page will no longer be accessiable.
Then the page will show: Application error: a client-side exception has occurred (see the browser console for more information).
![屏幕截图 2023-01-16 205115](https://user-images.githubusercontent.com/36598604/212682409-94d45be4-e9f7-4d0d-a409-3f7d0a05e9d5.png)

**Comment by DIYgod** [comment]
Sorry, I just saw your issue. This problem has already been fixed. If you still have any issues, please feel free to reopen it.
