### ISSUE TITLE
无法访问 cname.xlog.app 导致自定义域名也无法访问

### ISSUE THREAD

**Issue by myesn** [Crossbell-Box/xLog#1795]
之前一直都好好的，从今天开始就无法访问 `cname.xlog.app` 了，这导致自定义域名也无法访问：

![image](https://github.com/Crossbell-Box/xLog/assets/18598579/480762b9-6005-4007-adb8-800618a9de43)
![image](https://github.com/Crossbell-Box/xLog/assets/18598579/2025ba24-3bce-40a1-8278-97a77049d811)

**Comment by twilightsay** [comment]
我还以为我自己的域名被墙了==

**Comment by markbang** [comment]
同样的问题，国内现在无法访问

**Comment by incubator4** [comment]
有可能是某些地区 DNS 的问题，我暂时把 IP 换了先，以后要是还有类似的问题，得考虑一下新的对策

**Comment by myesn** [comment]
貌似原来的 IP 在整个国内都无法访问，新 IP 现在可以访问了，感谢😊

**Comment by incubator4** [comment]
> 貌似原来的 IP 在整个国内都无法访问，新 IP 现在可以访问了，感谢😊

主要是这是 GCP 的 IP，所以感觉被封的风险可能会比较高，最好的情况是有良好的网上环境
