### ISSUE TITLE
Remove usage of Cloudflare's IPFS gateways

### ISSUE THREAD

**Issue by TonyRL** [Crossbell-Box/xLog#1796]
## Motivations

Blog posts: https://blog.cloudflare.com/cloudflares-public-ipfs-gateways-and-supporting-interplanetary-shipyard

> All traffic using the **cloudflare-ipfs.com** or **cf-ipfs.com** hostname(s) will continue to work without interruption and be redirected to **ipfs.io** or **dweb.link** until **August 14th, 2024**, at which time the Cloudflare hostnames will no longer connect to IPFS and all users must switch the hostname they use to **ipfs.io** or **dweb.link** to ensure no service interruption takes place.

**Comment by DIYgod** [comment]
Thank you for the reminder, but we are using our own paid IPFS service, not Cloudflare's IPFS gateways.

**Comment by TonyRL** [comment]
I think it will break `getCharacterColors`.
https://github.com/Crossbell-Box/xLog/blob/55a90a4dea2f3723483910b7a97892eca7b2d0dc/src/queries/site.server.ts#L211-L216
https://github.com/Crossbell-Box/xLog/blob/55a90a4dea2f3723483910b7a97892eca7b2d0dc/src/lib/ipfs-parser.ts#L10-L19

**Comment by DIYgod** [comment]
You are right, thank you so much, removed in 92c113cef9c3f4afa847b2ff09632fd882e7097f
