### ISSUE TITLE
未初始化的代码块与预览的BUG

### ISSUE THREAD

**Issue by qinfengge** [Crossbell-Box/xLog#1828]
在编辑文章时，如果插入代码块，则直接触发报错
![image](https://github.com/Crossbell-Box/xLog/assets/35164697/67a1ad16-c26f-4883-87ec-dd9a65dcacd4)
![image](https://github.com/Crossbell-Box/xLog/assets/35164697/909d5245-6ddd-498c-9d40-4706e153defe)

除非关闭右侧的预览，或声明代码块的语言
![image](https://github.com/Crossbell-Box/xLog/assets/35164697/a243b886-456c-4827-a478-25478004380c)

此问题在1个月前我编写文章时似乎并没有出现

**Comment by DIYgod** [comment]
Fixed in 9b374cc1e4e58d8376976750efeeec48b6c7dd74
