### ISSUE TITLE
自定义 domain 时，无法通过文章链接直接访问

### ISSUE THREAD

**Issue by yjl9903** [Crossbell-Box/xLog#1829]
Reproduce: Open https://blog.onekuma.cn/server-webdav-jellyfin

It will render the content in an instant, but soon display a error log:

![image](https://github.com/Crossbell-Box/xLog/assets/30072175/9c791ce6-567e-4777-bf65-c007d0451d20)

**Comment by DIYgod** [comment]
Fixed in 9b374cc1e4e58d8376976750efeeec48b6c7dd74
