### ISSUE TITLE
功能: 在设置中添加语言切换

### ISSUE THREAD

**Issue by cloudflypeng** [Crossbell-Box/xLog#1881]
当前切换语言在页脚,但是看的时候信息流会自动加载导致我很难点到页脚,是否可以在设置中增加语言选择.
如果需要的话,我可以做这个

**Comment by cloudflypeng** [comment]
感觉设置里面是设定网站元数据的, 我添加进去了以后感觉并不合适, 
<img width="721" alt="image" src="https://github.com/Crossbell-Box/xLog/assets/44285412/9ac4bc74-f6f2-472a-8edf-40d69745fa27">

或许放在这两个地方会不会更好
![image](https://github.com/Crossbell-Box/xLog/assets/44285412/971d5fcc-cc97-4b00-82c7-48b7f2ce3a27)

**Comment by DIYgod** [comment]
下拉菜单里也可以，按钮就太占地方了
