### ISSUE TITLE
黑暗模式图标问题: github‘和 x 本身是黑色的, 在黑暗模式需要更换

### ISSUE THREAD

**Issue by cloudflypeng** [Crossbell-Box/xLog#1913]
<img width="464" alt="image" src="https://github.com/Crossbell-Box/xLog/assets/44285412/4b29f7a6-678b-4097-86d6-9f87a7013d0c">
<img width="260" alt="image" src="https://github.com/Crossbell-Box/xLog/assets/44285412/be703dbf-506f-44a3-aa81-49a22f04cfc5">

**Comment by EightEggs** [comment]
Steam的图标也是黑色的
