### ISSUE TITLE
我自己写的文章看不了了，无法打开近期（两个月前）写的文章，更久的文章可以打开，有复现办法

### ISSUE THREAD

**Issue by kmq116** [Crossbell-Box/xLog#2134]
首先点击我的首页地址，可以看到有这么些个文章
https://coderco.xlog.app/
![image](https://github.com/user-attachments/assets/757c0bc9-4673-4108-b419-28cd906cded4)
然后点击第一个文章
![image](https://github.com/user-attachments/assets/10705214-2cd7-48d7-9687-905133e68013)
可以看到下面的报错
![image](https://github.com/user-attachments/assets/b63641ff-4171-42b6-a1f1-a9634f102d01)
地址访问了，但是没有返回值
![image](https://github.com/user-attachments/assets/b6d58b7b-ff4d-42d2-a4b7-13e34b68ca87)
![image](https://github.com/user-attachments/assets/fad32ff0-7bc7-478d-bee0-6f8605f5e5ee)

**Comment by enpitsuLin** [comment]
看了下似乎是你的这个图片导致的问题，应该是有防盗链机制导致的

![](https://api.dicebear.com/6.x/bottts-neutral/svg?seed=53048)

**Comment by kmq116** [comment]
> 看了下似乎是你的这个图片导致的问题，应该是有防盗链机制导致的，应该是文章内容有这个图片吧？可以尝试移除试试
> 
> ![](https://camo.githubusercontent.com/2b59bf12e41b9a5c2fc0ec30b40d81550e6066d327d378729517da73317ea3a5/68747470733a2f2f6170692e64696365626561722e636f6d2f362e782f626f747474732d6e65757472616c2f7376673f736565643d3533303438)

这个图片是我的头像🥲，我换了个头像之后就可以了
