### ISSUE TITLE
I can't publish my post

### ISSUE THREAD

**Issue by FreeMagic200** [Crossbell-Box/xLog#2179]
As mentioned in the title and in Issue #2177, I am unable to publish my post.

**Comment by FreeMagic200** [comment]
![image](https://github.com/user-attachments/assets/17745c16-b22c-4089-a654-e9db31aa11ff)
I also find the duplicate content above to be abnormal.

**Comment by andrewji8** [comment]
raise the same question

**Comment by mancuoj** [comment]
一样，发了三次都是显示发布成功，但查看是 404

**Comment by enpitsuLin** [comment]
try disable Operator Sign should help, that feature still work but timeout error may occur. 

sign with wallet by yourself, This issue has been present for quite while

**Comment by andrewji8** [comment]
![Screenshot_9](https://github.com/user-attachments/assets/7aed6ab5-cec8-415e-be80-29f4bf872acb)
![Screenshot_10](https://github.com/user-attachments/assets/a8459981-07de-4c9d-8be1-6c5a521bbd10)
why?I can't publish my post?

**Comment by songkeys** [comment]
Sorry about this! This issue has just been resolved.

This situation occurred if you're using the Operator Sign or Email Account, as the agent wallet had run out of balance. We've already deposited some $CSB into it to fix the problem. Try again please.

Let me know if you still have the same problem.
