### ISSUE TITLE
Why can't I post a blog when I have enough coins?

### ISSUE THREAD

**Issue by andrewji8** [Crossbell-Box/xLog#2181]
![Screenshot_7](https://github.com/user-attachments/assets/4b364215-ba7f-47bc-ac5c-d654dbb0f62d)
![Screenshot_11](https://github.com/user-attachments/assets/5e91f52d-4fbe-4f7a-bd18-dec9c2ef6105)

**Comment by songkeys** [comment]
https://github.com/Crossbell-Box/xLog/issues/2179#issuecomment-2437049327
