### ISSUE TITLE
Mint Character失败

### ISSUE THREAD

**Issue by belijojo** [Crossbell-Box/xLog#2192]
我能用我的metamask连接和登录xlog，但在mint Character步骤一直失败，提示是Error while creating character.Log with topic CharacterCreated not found。交易详情的提示是 Error: (Awaiting internal transactions for reason)。

**Comment by belijojo** [comment]
![屏幕截图 2024-12-02 205716](https://github.com/user-attachments/assets/21d9a32d-d3bc-4632-a6d2-2ac048334396)

**Comment by AlexMa2011** [comment]
请问是如何解决的？
