### ISSUE TITLE
Custom RSS Link

### ISSUE THREAD

**Issue by ImSingee** [Crossbell-Box/xLog#220]
I'm planning to migrate my existing blog to xlog. But there's one issue:

My old atom RSS link is `/atom.xml` but the xlog's is `/feed/xml`

Is it possible to add a feature to customize the RSS link?

**Comment by DIYgod** [comment]
Thanks, `/atom.xml` is now redirected to `/feed/xml`. https://github.com/Crossbell-Box/xLog/commit/11fc759533b30c3db6f7459053c058f9ea16433c
