### ISSUE TITLE
Optimize the behavior of slash in slug

### ISSUE THREAD

**Issue by ImSingee** [Crossbell-Box/xLog#223]
There's some misbehavior if the custom slug contains slash.

1. After being restored from drafts, the `/` is replaced by `%2F`.
2. After publishing, click the `view posts` link will be redirected to a 404 page.
3. The `/` is being replaced by `%2F` in the published post

It's useful if the slash remains other than replaced by `%2F`. I think this can be optimized.

**Comment by DIYgod** [comment]
Thanks, slug now is restricted to only allow letters, numbers, hyphens, and underscores. https://github.com/Crossbell-Box/xLog/commit/8324beaa096cd0bf0dcb6a7a6e3c26bce090d3bb
