### ISSUE TITLE
Unpublish behaviour

### ISSUE THREAD

**Issue by ImSingee** [Crossbell-Box/xLog#224]
It seems that the `unpublish` is the same as the `delete` and cannot be restored by any means.

But I think, because of the name, the behavior may need to be changed:

1. Hide it from the published site
2. Still can be seen from the drafts (or even a new category called `unpublished`)
3. The data is still stored and synced (as opposed to local drafts)

And there may be another function just called delete.

**Comment by DIYgod** [comment]
Thanks, the `unpublish` has been changed to `delete`.  https://github.com/Crossbell-Box/xLog/commit/10b71cf644d054615e3be6af91bebd03280988ce
