### ISSUE TITLE
Math equations are not rendered in XPM (xLog Preferred Markdown)

### ISSUE THREAD

**Issue by Soptq** [Crossbell-Box/xLog#235]
Math equations demonstrated in the official xlog [blog](https://xlog.xlog.app/xfm) are not rendered.

<img width="766" alt="screenshot" src="https://user-images.githubusercontent.com/32592090/225842568-8f6c10ba-d9eb-43e4-9cc8-84455b2e6548.png">

**Comment by DIYgod** [comment]
The support for math equations can lead to some parsing errors, such as the following paragraph, so I temporarily disabled it. Now I have re-enabled it on dev branch.

```
We are hosting a writing competition on xLog - $500 USDT in prizes are up for grabs. ($200 first place, $100 for 2nd, 3rd, and 4th place)
```

Although `\$` can be used to avoid parsing errors, it will create additional burden for users. I am still looking for a better solution.

**Comment by DIYgod** [comment]
Currently, support for single dollar sign syntax has been removed and only double dollar signs can be used to trigger it (which also supports inline).
