### ISSUE TITLE
关于移动端端界面

### ISSUE THREAD

**Issue by zsakvo** [Crossbell-Box/xLog#245]
您好，目前移动端的后台功能，尤其是在进行撰写，预览等操作时依旧稍显不便。请问有这方面的更新计划或者路线图吗？
如果想贡献相关功能，请问要如何参与？是否有对应的设计稿等作为参考？ 
谢谢。

**Comment by DIYgod** [comment]
您好，近期还没有相关计划，也没有设计稿，如果可以贡献就太好了，请放心提交 pr，不影响现有功能就没问题

**Comment by zsakvo** [comment]
好的 👌🏻  我尝试弄一下
