### ISSUE TITLE
Enhancing "Operator Sign" Icon Visibility for Better UX

### ISSUE THREAD

**Issue by sxzz** [Crossbell-Box/xLog#268]
https://github.com/Crossbell-Box/xLog/blob/cc3f8be02f7959f252cc819fbacbd3bdfc1967b0/src/components/common/ConnectButton.tsx#L126-L129

The clarity of these two icons is insufficient. It is highly recommended to substitute them with more recognizable icons, such as Apple's emoji or add color to enhance their visibility.

The same issue applies to xChar.

![image](https://user-images.githubusercontent.com/6481596/227739530-5bcf49d7-e795-424d-8010-68504e0c33e2.png)
![image](https://user-images.githubusercontent.com/6481596/227739546-acbaf7b7-0925-4807-aff1-a3772b9261f0.png)

**Comment by DIYgod** [comment]
I deliberately made it not obvious because the operator sign is not a function that must be enabled, I don't want to stress the users.

**Comment by sxzz** [comment]
But I think it's should be slightly more visible. Every time I have to zoom in the page to check if it's enabled. It's tooooo small and hard to figure out

**Comment by DIYgod** [comment]
It is reasonable, perhaps we can add low saturation colors.
