### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by sxzz** [Crossbell-Box/xLog#269]
As someone who often works late at night or in low-light environments, I find that a Dark Mode would be immensely helpful in reducing eye strain and making the application more comfortable to use for extended periods of time. I'm sure many other users would also appreciate this feature.

**Comment by Innei** [comment]
@sxzz 来都来了，不来写下第一个需求么，还是自己的。[手动狗头]

**Comment by Innei** [comment]
#312
