### ISSUE TITLE
Slug should not contain `/`

### ISSUE THREAD

**Issue by Songkeys** [Crossbell-Box/xLog#27]
Check https://fblauer.xlog.app/ for an error when trying to view this article:

<https://fblauer.xlog.app/What-does-your-ideal-future-internet-/-web3-look-like-in-five-years?>

**Comment by Candinya** [comment]
need something like `encodeURIComponent(slug)`
like https://fblauer.xlog.app/What-does-your-ideal-future-internet-%2F-web3-look-like-in-five-years%3F is fine

**Comment by DIYgod** [comment]
Fixed ed27a48db459c5a5c38431b398fc72d3a331e541
