### ISSUE TITLE
custom domain issue

### ISSUE THREAD

**Issue by jiansongy** [Crossbell-Box/xLog#28]
I've tried to enter custom domain (say, cydog.cn), but I can't enter the "_xlog-challenge." in the TXT DNS record, as this is an unacceptable input. But later, I find a solution and works fine. 

I need to enter custom domain (with www, like www.cydog.cn), then I can enter the "_xlog-challenge.www" in the TXT of DNS record. Please note this issue. 

Thanks for your great product, and I will tell more friends to use it. 

Jason in Beijing

**Comment by Candinya** [comment]
What about trying `_xlog-challenge` (remove the ending dot) 👀
(Should be a front-end displaying bug

**Comment by DIYgod** [comment]
@Candinya is correct, you should use `_xlog-challenge` as the record name, I have fixed the front-end display in https://github.com/Crossbell-Box/xLog/commit/bb4344e7f1b0133a27c6494b84b30bf9a30f311c
