### ISSUE TITLE
渲染问题

### ISSUE THREAD

**Issue by aornus** [Crossbell-Box/xLog#284]
## 标题渲染
似乎在xlog中，四级标题往后都不能正确渲染，比如四级标题都会被渲染成1.1等。

标题渲染错误示例文章：[2w字长文-货币价值模型，黄金、法定货币与比特币](https://mrcai.xlog.app/03--huo-bi-jia-zhi-mo-xing--huang-jin--fa-ding-huo-bi-yu-bi-te-bi-md)
![标题渲染出错](https://user-images.githubusercontent.com/69356310/229980913-8e961b78-cc57-4a24-a2ed-f3662fd3a640.png)

## 引用渲染
当在文中使用`[^1]`，文末使用`[^1]:参考自XXX`时，不论点击文中还是文末footnotes的箭头符号“↩”都不能跳转到对应位置。

**Comment by DIYgod** [comment]
Title style has been added in 5d4f99fcf86dafc2f8fef1ffbd84b7688a77c09f

Citation syntax still needs to be done.
