### ISSUE TITLE
[Bug] 底部社交图标正确配置后未渲染

### ISSUE THREAD

**Issue by yusixian** [Crossbell-Box/xLog#286]
Social 配置正常了反而图标未渲染，如图，因为没有回落到兜底icon，所以是配置正确了
![image](https://user-images.githubusercontent.com/43498495/230098147-07c6fd58-0710-48fa-b5b6-f81d5fb807b3.png)

大致定位问题应该是 Platform 中给Image传入的是 syncMap[platform]?.icon = ‘/assets/social/telegram.svg’，是Next中的资源路径，然而使用了Image组件，该Image组件内部加了这样一些代码：

![image](https://user-images.githubusercontent.com/43498495/230097481-16e33a63-29ff-47f3-b9f1-e930bd8247cf.png)

```typescript
  src = toIPFS(src)
  const [paddingTop, setPaddingTop] = React.useState("0")
  const [autoWidth, setAutoWidth] = React.useState(0)
  const autoSize = !width && !height && !fill
  const noOptimization = className?.includes("no-optimization")

  try {
    new URL(src)
  } catch (error) {
    return null
  }
```
其中 toIPFS 这个函数我也看了，对Next的路径没什么影响

```typescript
export const toIPFS = (url: string) => {
  return url
    ?.replaceAll(IPFS_GATEWAY, IPFS_PREFIX)
    .replaceAll("https://gateway.ipfs.io/ipfs/", IPFS_PREFIX)
    .replaceAll("https://ipfs.io/ipfs/", IPFS_PREFIX)
    .replaceAll("https://cf-ipfs.com/ipfs/", IPFS_PREFIX)
    .replaceAll("https://ipfs.4everland.xyz/ipfs/", IPFS_PREFIX)
    .replaceAll("https://rss3.mypinata.cloud/ipfs/", IPFS_PREFIX)
}
```
这是 [new URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) 的说明
总结：原因应该是 new URL(src) 这一步的时候抛出错误了，但是catch了直接返回null了，也没有console.error。

**Comment by DIYgod** [comment]
Thanks, it has been fixed in 3d4cb2d2647b23974c81d7fd512f54c7bb85af0a
