### ISSUE TITLE
[Bug] Activity页面有时无法渲然最新的Posts

### ISSUE THREAD

**Issue by Royc30ne** [Crossbell-Box/xLog#288]
Activity页面有时无法渲然最新Post，有时候需要按一下Enable AI Filtering才能刷新到最新消息

**Comment by DIYgod** [comment]
It should be caused by persistent caching. It has been fixed in e00be336bd184cefc4c09679e44eba424272e7bf. If the problem still exists, please feel free to reopen.

**Comment by Royc30ne** [comment]
Thanks for replying, have a good night!
