### ISSUE TITLE
[feature] add xSync navigation 

### ISSUE THREAD

**Issue by yusixian** [Crossbell-Box/xLog#302]
我看到tg动态、twitter等是会被xSync同步到文章的，但只有默认生成的短链接，读者没有一个能快速看到这些被同步的文章的渠道

是否能将同步的文章自动打一个tag或者内置页面？
![image](https://user-images.githubusercontent.com/43498495/230739336-5185b449-c120-43a8-915f-ebd2e8107fe0.png)
![image](https://user-images.githubusercontent.com/43498495/230739416-3b80c281-1043-49a0-973f-feb295ec100f.png)

**Comment by DIYgod** [comment]
The synchronized content can be viewed in [xFeed](https://xfeed.app/). xSync, xFeed and xLog are independent products.
