### ISSUE TITLE
Feature Request 文章插入音乐播放器

### ISSUE THREAD

**Issue by SevenOutman** [Crossbell-Box/xLog#319]
从 APlayer 追星到 xLog，最近想要尝试把自己的 weekly 搬到 xLog 上，但是我的 weekly 开头会有一个 APlayer 放本周收藏的音乐，目前 xLog 上好像没有 workaround，这一点阻碍我搬过来…不知道是否可以加类似的功能

https://doma.land/weekly/23w13+14/
<img width="696" alt="image" src="https://user-images.githubusercontent.com/8225666/231406330-719cba69-a9e7-4da0-b4d1-ff5db1782315.png">

FYI，我的 weekly 中 APlayer 用的是自己封装的 `aplayer-react`，歌曲信息是通过 NetEaseMusicApi 拉的，方案写在 [https://doma.land/blog/为你的 React 应用添加音乐播放器/](https://doma.land/blog/%E4%B8%BA%E4%BD%A0%E7%9A%84%20React%20%E5%BA%94%E7%94%A8%E6%B7%BB%E5%8A%A0%E9%9F%B3%E4%B9%90%E6%92%AD%E6%94%BE%E5%99%A8/)

**Comment by Innei** [comment]
@SevenOutman 想知道你是如何在文章（markdown）中定义 aplayer。或许是 html 标签 or 特殊语法

**Comment by SteveYuOWO** [comment]
> @SevenOutman 想知道你是如何在文章（markdown）中定义 aplayer。或许是 html 标签 or 特殊语法

maybe add parse the audio tag? https://www.w3schools.com/html/html5_audio.asp

**Comment by SteveYuOWO** [comment]
> @SevenOutman 想知道你是如何在文章（markdown）中定义 aplayer。或许是 html 标签 or 特殊语法

html audio tag? https://www.w3schools.com/html/html5_audio.asp

**Comment by SevenOutman** [comment]
> @SevenOutman 想知道你是如何在文章（markdown）中定义 aplayer。或许是 html 标签 or 特殊语法

@Innei 在我的博客中，是在 markdown 的 frontmatter 中添加了 `songs` 数组记录歌曲信息，然后在文章的 layout 组件中根据是否有 `songs` 来渲染一个 APlayer 的。（也就是[这篇文章](https://doma.land/blog/%E4%B8%BA%E4%BD%A0%E7%9A%84%20React%20%E5%BA%94%E7%94%A8%E6%B7%BB%E5%8A%A0%E9%9F%B3%E4%B9%90%E6%92%AD%E6%94%BE%E5%99%A8/)中记载的方法）

我起初也尝试过直接在 markdown 正文中声明 aplayer，想要借鉴 [`gatsby-remark-audio`](https://www.gatsbyjs.com/plugins/gatsby-remark-audio/) 提到的这种 pattern，但是对于要声明多首歌曲的播放列表的场景没有想到比较优雅的形态。并且我的文章中显示播放器的位置是固定在文章前面的，不需要 per 文章地指定播放器的位置，所以最后改成了目前的 frontmatter 的方案。

**Comment by DIYgod** [comment]
已经上线了，撒花！
