### ISSUE TITLE
feat: add table, text color, emoji 增加表格，文本颜色，emoji

### ISSUE THREAD

**Issue by ercwangwh** [Crossbell-Box/xLog#320]
目前没有表格功能，表格我只能截图放进去，要提取表格里的内容很不方便。
还有就是文本颜色和emoji，缺少颜色和emoji写文章和看文章都很难找到重点，目前只能通过标题来定位重点。

**Comment by greyhao** [comment]
Markdown 支持表格、设置字体颜色
emoji：输入法输入之后可以看到正常展示  不太理解缺少是什么意思？

**Comment by ercwangwh** [comment]
emoji是我疏忽了，是可以从输入法输入。可能我习惯了像twitter那样在它的picker里面找。
table我看官方文档是有支持，只是我在editor上找不到，而且我通过复制其他文章的table也无法正确显示。
<img width="370" alt="image" src="https://user-images.githubusercontent.com/45984686/231941350-77451d0f-f441-4626-b67f-cd74926125fa.png">
文本颜色你意思是在自定义CSS里面修改吗，这个我觉得也不是很方便。希望能直接修改。
总体我觉得编辑器还是稍微欠缺了一些功能，写文章跟写微博不一样，还是需要多一点的功能。

**Comment by daidr** [comment]
在编辑器中能够使用一些安全的HTML，比如想要自定义文字颜色，你可以像下面这样做
![image](https://user-images.githubusercontent.com/18638914/231949149-beecd80b-954a-4ffb-9386-eac94dc6feb0.png)

**Comment by daidr** [comment]
你可以使用下面这种语法插入表格
```markdown
| 第一列        | 第二列     | 第三列    |
|-------------|-----------|-----------|
| 一些内容     | 123         | 456         | 
| 一些内容     | 789         | 987         |
```

![image](https://user-images.githubusercontent.com/18638914/231950817-24b23361-3b0d-4f1a-954a-9e111dc7d790.png)

也支持表格元素居中，具体可以查看Markdown语法教程

**Comment by ercwangwh** [comment]
学习了，谢谢。暂时解决了我的问题。
Markdown对于普通人还是过于“硬核”了，我感觉还是有点难受，希望后续版本能继续优化写作体验。

**Comment by DIYgod** [comment]
More shortcuts have been added(https://github.com/Crossbell-Box/xLog/pull/338), and more examples have been added to the [help page](https://xlog.xlog.app/xfm)
