### ISSUE TITLE
Incomplete display when only one post

### ISSUE THREAD

**Issue by SteveYuOWO** [Crossbell-Box/xLog#325]
The drop-down list seems to have been trimmed in dashboard page.

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/41619339/231611151-c1aa33dc-ed88-46d7-b7dc-8b7200cb59ce.png">

**Comment by DIYgod** [comment]
I did not reproduce the issue. There was a style adjustment made yesterday, and I am not sure if it fixed the problem. Can you confirm if the issue still exists now?

**Comment by SteveYuOWO** [comment]
Has been fixed. @DIYgod
