### ISSUE TITLE
[Bug] Certain article content will cause xLog to crash

### ISSUE THREAD

**Issue by daidr** [Crossbell-Box/xLog#343]
When the following content is entered in the editor, xLog crashes.

This can also affect the article page.

```
<img>
```

prod:
![image](https://user-images.githubusercontent.com/18638914/232131191-9841e57a-e4fa-49ce-8d62-33e9a6bad5c6.png)

dev:
![image](https://user-images.githubusercontent.com/18638914/232131524-27608893-7330-493d-9551-fc5b55b2196b.png)

**Comment by DIYgod** [comment]
Fixed in d16a455ed6d6f5b346706aaf871b5c5ac192e92d
