### ISSUE TITLE
[DX & Performance] NextJS 13 Server Actions and App Router mode

### ISSUE THREAD

**Issue by Innei** [Crossbell-Box/xLog#345]
The issue may be a long-term project, and it is also a long-term problem that needs to be considered in subsequent maintenance and iteration.

- Granular components：
	- Editor Component improve：
		- #389
		- #411
- LCP：
	- https://github.com/Crossbell-Box/xLog/commit/05b96e3a49dfdf5134fdcefe55790732e0c6af78

Follow the new trends in front-end development. NextJS Server Actions and App Router mode.

- https://github.com/Crossbell-Box/xLog/tree/feature/nextjs-app-router

**Comment by Innei** [comment]
目前的 `_app`
<img width="629" alt="image" src="https://user-images.githubusercontent.com/41265413/232234453-1da76753-737f-4d62-b4e3-8366d4d008ca.png">

**Comment by Innei** [comment]
文章预览的 lighthous performance 也迭了，有大量 unsed javascript 在首屏被执行了。需要考虑优化 `_app`

**Comment by Innei** [comment]
re-render 以 editor 为例。

https://user-images.githubusercontent.com/41265413/232234769-af40755b-3e19-4d28-b6a7-6aafbe12e87e.mov

**Comment by Innei** [comment]
我很乐意在空闲时间，开始跟进这些问题。

**Comment by DIYgod** [comment]
The size of the `_app` was a disaster caused by the pinyin module. I have separated it in 05b96e3a49dfdf5134fdcefe55790732e0c6af78, so it should be much better now.

<img width="428" alt="image" src="https://user-images.githubusercontent.com/8266075/232260166-ec050406-3800-468c-9b6f-25ec1e29b67b.png">

**Comment by iamdin** [comment]
> 



> 这个 issue 可能是个长期项目，也是在后续维护和迭代中需要考虑的长期问题。
> 
> * [ ]  首屏加载时间 和 入口 `_app` 体积过大。
>   
>   * [ ]  粒度化拆分 layout
>   * [ ]  适度使用 lazyload 组件，从 `_app` 拆离
>   * [ ]  React Supense
> * [ ]  页面 re-render 次数过多
>   
>   * [ ]  粒度化抽离组件
> 
> 首屏优化：
> 
> * [05b96e3](https://github.com/Crossbell-Box/xLog/commit/05b96e3a49dfdf5134fdcefe55790732e0c6af78)
> 
> 编辑器优化：
> 
> * [refactor: reduce rerendering in editor edit #389](https://github.com/Crossbell-Box/xLog/pull/389)

下个双月 OKR 有了 🐶，下来跟你对齐一下
