### ISSUE TITLE
DPlayer support

### ISSUE THREAD

**Issue by SteveYuOWO** [Crossbell-Box/xLog#362]
As a user, having a video tag on xlog is a cool thing to blog about.Users can upload as much video content as they want permanently on the ipfs blockchain without fear of regulatory removal. Support drag and drop videos on xlog and live preview on the editor.

Support [DIYgod/DPlayer](https://github.com/DIYgod/DPlayer).

**Comment by SteveYuOWO** [comment]
Since [DIYgod/DPlayer](https://github.com/DIYgod/DPlayer) does not support react, Is there a recommended repo of `react-dplayer`?

**Comment by DIYgod** [comment]
I am a little worried that the video files are too large, which will bring significant pressure on storage and bandwidth.

**Comment by SteveYuOWO** [comment]
> I am a little worried that the video files are too large, which will bring significant pressure on storage and bandwidth.

Indeed. In terms of storage, before that there was video storage on ipfs. Direct access video from ipfs doesn't seem to be a problem. In terms of bandwidth, there's still something to consider.

**Comment by SteveYuOWO** [comment]
ux interaction is also important, as long videos take longer to upload. Perhaps tooltip needs to support a progressbar.

**Comment by DIYgod** [comment]
IPFS also requires money to ensure that files are continuously stored, and the cost is not cheaper than centralized storage. The current cost is borne by Crossbell, so there is no pressure for audios and images, but the size of videos that are several gigabytes still puts some pressure.

**Comment by SteveYuOWO** [comment]
> IPFS also requires money to ensure that files are continuously stored, and the cost is not cheaper than centralized storage. The current cost is borne by Crossbell, so there is no pressure for audios and images, but the size of videos that are several gigabytes still puts some pressure.

Considering the cost factor, it may be necessary to limit the video size to less than 10M (this size may need to be calculated and modified by crossbell), or if the size exceeds the limit, users may pay eth expenses later.

**Comment by DIYgod** [comment]
You are right, limiting the size is a good idea.
