### ISSUE TITLE
排版细节优化

### ISSUE THREAD

**Issue by lencx** [Crossbell-Box/xLog#371]
markdown 对 \`xxx\` 的解析排版似乎有问题，我理解它应该是 inline-block

![image](https://user-images.githubusercontent.com/16164244/232675342-c068b66f-1720-4f79-abe5-19202663007e.png)

**Comment by daidr** [comment]
是指这样么？

修改前：
![image](https://user-images.githubusercontent.com/18638914/232679485-a8fcecd1-56d4-4acb-aef4-2bb34810d7d4.png)

修改后：
![image](https://user-images.githubusercontent.com/18638914/232679506-40eff130-1331-46ff-a38b-2bc087901d46.png)

**Comment by lencx** [comment]
是的，\`xxx\` 解析成 `<code>` 标签没问题，但是它不应该变成 block 元素。这个在描述代码中会经常出现，用来标记变量之类的。
