### ISSUE TITLE
提供注销角色的能力

### ISSUE THREAD

**Issue by devyujie** [Crossbell-Box/xLog#375]
莫名其妙的多mint了个角色，然后每次链接页面时都要切换一下，如果能注销角色就好了

**Comment by DIYgod** [comment]
Crossbell has a public component that provides deletion function, and now an entry has been added to the settings in the dashboard. https://github.com/Crossbell-Box/xLog/commit/12926446ee1da3860d324399d9b32f3cca4ab76d
