### ISSUE TITLE
[Feature Request] Notification Modal Darkmode Support

### ISSUE THREAD

**Issue by PerfectPan** [Crossbell-Box/xLog#381]
It would be better to have darkmode support for notification modal.

![CleanShot 2023-04-19 at 00 28 49@2x](https://user-images.githubusercontent.com/24316656/232843259-5587a2db-985b-4e40-a255-8074645472bc.png)

**Comment by runjuu** [comment]
Feature added in https://github.com/Crossbell-Box/xLog/pull/446
