### ISSUE TITLE
增加对 AI 总结的控制按钮

### ISSUE THREAD

**Issue by devyujie** [Crossbell-Box/xLog#393]
能否增加一个按钮让用户选择是否开启 AI 总结，我发现当文章只有一张图片时，顶部那里会闪一下~应该是没检测到有文字

![1](https://user-images.githubusercontent.com/48620527/233307890-cae8c6ba-3b1a-4c21-a110-ea354fd3e737.gif)

**Comment by dohooo** [comment]
可能加一个过渡动画是个好的优化方式，确定没内容后，通过动画收起总结栏。 🤔

**Comment by DIYgod** [comment]
It has now been changed to fully server-side output, so this problem will not occur again.
