### ISSUE TITLE
[UI Bug]  搜索栏图标挡住了部分文字，导致鼠标无法把光标移到文字前而是触发搜索

### ISSUE THREAD

**Issue by birdgg** [Crossbell-Box/xLog#408]
搜索栏图标挡住了文字， 导致鼠标无法把光标移到文字前而是触发搜索

<img width="695" alt="Screenshot 2023-04-22 at 19 57 08" src="https://user-images.githubusercontent.com/4584859/233783326-bae0852a-26ac-4401-98e5-af7d72bb3de9.png">

**Comment by RaineySpace** [comment]
我这边没有发现这个问题，会不会是你的自定义css修改了这边的样式

<img width="484" alt="image" src="https://user-images.githubusercontent.com/10717953/233821571-cbd437af-eef3-4f9b-b18c-200451d15f21.png">

**Comment by Innei** [comment]
This issus is fixed in #414
