### ISSUE TITLE
[Feature Repuest] More social support

### ISSUE THREAD

**Issue by enpitsuLin** [Crossbell-Box/xLog#422]
## Motivation

Currently, xLog supports only [14 platforms](https://github.com/Crossbell-Box/xLog/blob/dev/src/components/site/Platform.tsx#L7). 

I think the future decentralized social platform obviously can't be only one specifying `domain`

In fact, there are already platforms like [mastodon](https://github.com/mastodon/mastodon) that have achieved decentralized social networking.

## Example

I think [elk](https://github.com/elk-zone/elk)'s way to adding social offers greater customization options. 

 Instead of specifying platform and identity, it allows users to choose icons, titles, and link URLs to create social links.

![image](https://user-images.githubusercontent.com/29378026/233937144-1f1859fb-c065-4fea-a90f-ed038d66a78e.png)

**Comment by DIYgod** [comment]
Yes, it may not be a domain in the future, but for now it is, and you have to have a domain to access it with a browser

I don't see the point of user choice either, Twitter account in general should just show the Twitter logo

I would also like to use a icon library, but haven't found a comprehensive one

**Comment by enpitsuLin** [comment]
@DIYgod 

IMO, social media links on xLog shouldn't be limited to a single domain. not for future, I think it's important to note that decentralized social platforms like `mastodon` let users from different websites can reach each other. 

Even if there are `mastodon` doesn't exist, users still might want to feature their email, custom URLs, or some little-known social media accounts within that section.

**Comment by DIYgod** [comment]
Email addresses also have URIs, such as mailto:i@diygod.me.

The problem may lie in that we should support custom URIs and icons.

**Comment by hyoban** [comment]
@DIYgod Here is a library of icons that I think fits nicely, you can import via iconify.

https://simpleicons.org

**Comment by DIYgod** [comment]
> Here is a library of icons that I think fits nicely, you can import via iconify.
> 
> [simpleicons.org](https://simpleicons.org)

Great discovery! I have already changed into it. f822b299150c268c60bd2225010f8a4b2eebf59f
