### ISSUE TITLE
Overall small UX/UI problems

### ISSUE THREAD

**Issue by jeff41101** [Crossbell-Box/xLog#427]
Mint related
1/ No cancellation on the mint modal, should return to the home page if click x
2/ Should set an input filter for name registration
Blogging
1/ Too many transactions ina time to just click thumbs up (three times to be precise)
2/ Maybe have a language category in the future, so Chinese reader & English reader can find their articles they want easier

**Comment by DIYgod** [comment]
These problems have all been resolved.
