### ISSUE TITLE
The sign up procedure may leak private information of users' Twitter account.

### ISSUE THREAD

**Issue by ksDreamer** [Crossbell-Box/xLog#434]
The sign up procedure may leak private information of users' Twitter account. I know that this is set for preventing the robot accounts. But if we can use email or other ways(phone numbers, other social medias etc.) That would be better. 
Sorry about knowing almost nothing about robot accounts （or say 机器人注册账号 in Chinese), maybe email or other ways cannot prevent the robot accounts. Just some naive thinking. 
xLog is wonderful. Go ahead!

**Comment by DIYgod** [comment]
Emails cannot prevent robots.

We are actively providing more verification methods, including a Discord bot. In the future, it can also be purchased for cryptocurrency to meet the needs of anonymous individuals.
