### ISSUE TITLE
Permission issue for GitHub Action `Next.js Bundle Analysis / analyze`

### ISSUE THREAD

**Issue by DIYgod** [Crossbell-Box/xLog#436]
The write permission is set [here](https://github.com/Crossbell-Box/xLog/blob/dev/.github/workflows/nextjs_bundle_analysis.yml#L20)，but you can actually see that the `pull-requests` permission is not properly granted, and I don't know why

<img width="378" alt="image" src="https://user-images.githubusercontent.com/8266075/234543465-34bde4ad-055d-4c86-a6a9-2cc3280ebb67.png">

There's also been feedback here that there's a problem with `create-or-update-comment` permissions https://github.com/peter-evans/create-or-update-comment/issues/84#issuecomment-1468084740

But RSSHub seems to be able to comment by default without even specifying permissions, see https://github.com/DIYgod/RSSHub/blob/master/.github/workflows/pr-deploy-route-test.yml#L79

I suspect that the `peter-evans/create-or-update-comment` action itself is the problem

**Comment by Innei** [comment]
@DIYgod  I just read github docs on the use of `GITHUB_TOKEN` . If it is a forked project, the `GITHUB_TOKEN` permissions are restricted.

<img width="607" alt="image" src="https://user-images.githubusercontent.com/41265413/234554360-81fd8ec7-9a18-4a79-ba1c-526337d144e9.png">

**Comment by Innei** [comment]
Change this default
<img width="857" alt="image" src="https://user-images.githubusercontent.com/41265413/234555102-dbfa4e08-71a5-4716-90fb-94a82cc038a5.png">

**Comment by Innei** [comment]
In #437, add `secrets.GH_TOKEN` for comment action. Go to repository secrets create `GH_TOKEN` field, and have a try

**Comment by DIYgod** [comment]
The personal access token is a very high permission token, it has write access to the entire repository, it is very unwise to use it for pull request, I still feel that commenting is an action that does not require special permissions, in addition to the RSSHub permissionless implementation of commenting, I also found another action that also does not require additional permissions: https://github.com/marketplace/actions/comment-pull-request

**Comment by Innei** [comment]
Same as before. Not working.

<img width="475" alt="image" src="https://user-images.githubusercontent.com/41265413/234593097-9546af46-e3c1-4220-96f0-7726d8beed0b.png">

**Comment by birdgg** [comment]
fix with `workflow_run`,  checkout [here](https://github.com/birdgg/learn-ci/tree/dev/.github/workflows)
idea from [here](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
@Innei

**Comment by birdgg** [comment]
> > fix with `workflow_run`, checkout [here](https://github.com/birdgg/learn-ci/tree/dev/.github/workflows?rgh-link-date=2023-04-26T14%3A15%3A34Z) idea from [here](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) @Innei
> 
> #437 I copy your workflow files, when `Next.js Bundle Analysis` done, but update pr-comment not trigger.

It need to be merged in dev to trigger

**Comment by birdgg** [comment]
Also the permissions part could be removed from analysis

```
# permissions:
#   contents: read # for checkout repository
#   actions: read # for fetching base branch bundle stats
#   pull-requests: write # for comments
```

**Comment by DIYgod** [comment]
Amazing discovery, no wonder the RSSHub workflow works.

Angry about why GitHub's documentation doesn't make this clear. 🥵
