### ISSUE TITLE
Fixed image size and image placeholder

### ISSUE THREAD

**Issue by DIYgod** [Crossbell-Box/xLog#440]
Discussion on fixed image size: https://discord.com/channels/976854077709369424/1099535870480109569

Placeholder can consider : https://plaiceholder.co/ 
From https://travis-397.xlog.app/blurred_images_loading_-nextjsmd

**Comment by Innei** [comment]
> Plaiceholder is a [Node.js](https://nodejs.org/en/) library. It's designed only to work in a Node.js environment, not the browser.

看上去只能用在 ServerSide，但是 xLog 的 Markdown Render 并不是都在服务端上做的

**Comment by Innei** [comment]
看了眼作者的博客是 SSG 的纯静态内容，可以在构建时生成相关的 blurData，动态的估计不好搞。还是得服务端支持下。
