### ISSUE TITLE
semantic class names for different sections on webpage

### ISSUE THREAD

**Issue by Songkeys** [Crossbell-Box/xLog#450]
Some users might need to further customize the webpage's sections. For example, to hide the ownership info on the bottom. We might need some more semantic classnames for them. E.g., `<section class="ownership-info">...</section>` for this one.

<img width="769" alt="image" src="https://user-images.githubusercontent.com/22665058/235054099-0894f1dd-541c-4abc-99f8-26fd61e8153a.png">

**Comment by Nanak360** [comment]
I can take up this issue and start working on it

**Comment by enpitsuLin** [comment]
any progress here?

**Comment by Nanak360** [comment]
> any progress here?
> 
> I have done some things on this topic but maybe need more work

Hey didn't get chance to work on this yet. Will be start working on this.

**Comment by Nanak360** [comment]
I have raised a PR for this issue. #546 
If any other changes are needed please let me know.

**Comment by Nanak360** [comment]
Are there any other things that the user might need to hide?
If so, I can add semantic tags and proper class names to them. 
AlsoI wanted to know if semantic tags are needed for each section irrespective of the user being able to hide it or now
