### ISSUE TITLE
Maximum call stack size exceeded ?

### ISSUE THREAD

**Issue by hwenjia** [Crossbell-Box/xLog#466]
上传图片时显示: Maximum call stack size exceeded

**Comment by Innei** [comment]
@hwenjia  请提供最小复现路径

**Comment by hwenjia** [comment]
我不知道怎么提供。但是今天又可以上传了。

**Comment by DIYgod** [comment]
Cannot reproduce, the issue will be closed. If there are still problems, please feel free to reopen it.
