### ISSUE TITLE
[Bug Report] Error in the sitemap.xml generation process

### ISSUE THREAD

**Issue by cjh0613** [Crossbell-Box/xLog#491]
Something is wrong with sitemap.xml

The URLs of any blog in the sitemap.xml are generated incorrectly, with `/undefined` being used as the path. And lastmod is the current time.

**Comment by SteveYuOWO** [comment]
@cjh0613 Indeed. Fixed the slug of undefined.

**Comment by SteveYuOWO** [comment]
Done in #493
