### ISSUE TITLE
[Feature] Custom cover

### ISSUE THREAD

**Issue by SteveYuOWO** [Crossbell-Box/xLog#498]
Sometimes the second image is more suitable for the cover image when publishing articles. Can Xlog support custom article cover image?

**Comment by birdgg** [comment]
You can set cover use this at beginning
```
<div style="display:none">
![cover](https://cover.com)
</div>
```

**Comment by SteveYuOWO** [comment]
@birdgg thank u, it worked.

**Comment by SteveYuOWO** [comment]
Maybe it's better to be an option during publish.

**Comment by DIYgod** [comment]
Done 49262e5b75b38e65bc3b5488c764d22fda6c5cef
