### ISSUE TITLE
The mouse hovers over the list of articles, but the link is wrong

### ISSUE THREAD

**Issue by jokereven** [Crossbell-Box/xLog#516]
![image](https://github.com/Crossbell-Box/xLog/assets/73232691/06f0f8c9-f495-4f6c-a535-67c2f9517016)

**Comment by DIYgod** [comment]
I'm not sure if it's a browser difference or if the issue has already been fixed. I can't reproduce it now. Can you help confirm whether the problem still exists?

**Comment by jokereven** [comment]
The problem was solved, Thank you for solving this problem.
