### ISSUE TITLE
[Feature] Request about "remark-emoji" render

### ISSUE THREAD

**Issue by skyonedot** [Crossbell-Box/xLog#525]
## Request

Request to add support for the ["remark-emoji"](https://github.com/rhysd/remark-emoji) rendering.

---

## Reason

Recently, I had the pleasure of using our Xlog as a personal blogging website, and it has been absolutely fantastic.

As a devoted Markdown user, I greatly appreciate using Typora as my preferred editor. One of its standout features is the ability to render icons, such as printing the word ": apple :"(remove the spaces)  to display the icon :apple: 

---

## Example 

In comparing my personal [blog](https://skyone.xlog.app/Sparrow-Wallet-Bitcoin) on the left and [Xlog](https://www.skyxuan.one/posts/Bitcoin-SparrowWallet) on the right, the differences are as follows:

![](https://raw.githubusercontent.com/skyonedot/picture-host/master/20230511220429.png)

**Comment by skyonedot** [comment]
Also, If you need, I can also help submit a PR to improve the relevant code.

**Comment by DIYgod** [comment]
Thank you so much for liking it! 

This feature is great, and I would be very grateful if it can be submitted as a pull request.

**Comment by skyonedot** [comment]
Fix it.
