### ISSUE TITLE
change chain may have caches

### ISSUE THREAD

**Issue by greyhao** [Crossbell-Box/xLog#545]
If current is not Crossbell chain, then do some transaction options, they will cant go well.

There is my step:
 * open xlog, and connected wallet
 * on other tab do something on ETH or other evm chain
 * open "settings" "social-platforms"
 * add social item
 * click "save"
 * click “change”
 * show "Failed to save"
 then unless I manually switch to crossbell in metamask or refresh the page, otherwise it will keep show "Failed to save".

when I use dapps seem don’t have same issue.

**Comment by runjuu** [comment]
Hi @greyhao , which wallet are you using?

**Comment by greyhao** [comment]
MetaMask (Chrome

**Comment by runjuu** [comment]
I couldn't reproduce the issues 🥲. I switched to Ethereum Mainnet on a different website, then switched back to xLog to update social platforms. Everything seems to be functioning well. Before the transaction confirmation prompt, there should be a network switch prompt from the MetaMask extension.

Could you provide the versions of your browser and wallet as well? Furthermore, are there any console errors when the 'Failed to save' message appears?

<img width="472" alt="image" src="https://github.com/Crossbell-Box/xLog/assets/12002941/9b656e2e-b182-4569-8c64-3a0ef2fcb535">

**Comment by greyhao** [comment]
" Before the transaction confirmation prompt, there should be a network switch prompt from the MetaMask extension. "
 yes, it is. But after click "Switch network" show "Failed to save". 

The version info:
  Chrome version:  113.0.5672.126 (arm64)
  MetaMaks version: 10.30.4
 
<img width="1201" alt="Pasted Graphic 62" src="https://github.com/Crossbell-Box/xLog/assets/107107440/76a09719-d208-44e9-863f-cff249169f47">

**Comment by runjuu** [comment]
@greyhao Sorry for the delay in responding. Would you mind updating us on whether the issue has been resolved?

**Comment by greyhao** [comment]
@runjuu  It's ok. It hasn't happened the last few times, and I think the issue has been resolved by self.
Thanks for your time. You can close this issue. Thank u again.
