### ISSUE TITLE
[Bug Report] Flicker on first render.

### ISSUE THREAD

**Issue by dohooo** [Crossbell-Box/xLog#548]
https://github.com/Crossbell-Box/xLog/assets/32405058/b775ce09-f191-4f16-9f9f-a00f3cb88cae

**Comment by birdgg** [comment]
Here's a solution use cookie https://github.com/vercel/next.js/discussions/47952

**Comment by dohooo** [comment]
> Here's a solution use cookie [vercel/next.js#47952](https://github.com/vercel/next.js/discussions/47952)

This approach does not apply to us. We support custom domain names and will lose cookies.
