### ISSUE TITLE
[Feature Request] Support for receiving email notifications for unread comments.

### ISSUE THREAD

**Issue by Innei** [Crossbell-Box/xLog#617]
Sometimes I forget to check the xLog dashboard and often miss readers' comments. Perhaps email notifications can be supported. We can use [Resend's](https://resend.com/) service to achieve this. The email template can be created using [React Email](https://react.email/). If needed, I am happy to implement the development of the email template.

**Comment by enpitsuLin** [comment]
That might should be an extra preference setting, I think this is a nice feature

**Comment by DIYgod** [comment]
This is a great idea! Since @birdgg is already working on mobile push notifications, it should be feasible to integrate email and web push notifications as well.

**Comment by birdgg** [comment]
@dohooo recommended me [novu](https://novu.co/), it also include email service.

**Comment by BarryYangi** [comment]
If possible, I think it would be great to add an optional email subscription feature that sends notifications to users about the latest blog updates, not just unread comments, by their favorite bloggers. Sometimes, I miss out on several days of updates from bloggers I like.

**Comment by birdgg** [comment]
> If possible, I think it would be great to add an optional email subscription feature that sends notifications to users about the latest blog updates, not just unread comments, by their favorite bloggers. Sometimes, I miss out on several days of updates from bloggers I like.

@BarryYangi  Currently, you can subscribe your favorite bloggers using rss. It is a better way than email subscription.
