### ISSUE TITLE
Product Plan for 2023.07

### ISSUE THREAD

**Issue by DIYgod** [Crossbell-Box/xLog#624]
## Creation

- Monthly/Weekly Creation Achievements #618
- Anonymous comments #619

## Tips (Between Users)

- Tipper Achievement
- Add tip activities and rankings to the homepage
- Periodic tip
- Simplify recharge process 

## Content Format

Transitioning from a text-based blogging community to a multimedia-focused community.

### Image Content (Image with Short Text) (Main)

- Emphasize cover image in text content

- Use different display formats in the list (not sure how to make it compatible with text content yet)

### Audio Content (Podcast) (Secondary)

- Optimize player, use a global player that is detached from the page and supports full-screen playback

- AI subtitles and summaries

### Video Content

Bandwidth cost is too high, maintain current situation for now, only allow small files.

## Consumption

- Content Classification #531
- Mobile App https://github.com/Crossbell-Box/xLog-mobile
- Email and Web Push Notifications #617

**Comment by runjuu** [comment]
As we begin to implement email notifications, would it be possible to also include an email subscription feature? 🤔

This would be beneficial for those audiences who may not be familiar with crypto wallets but are interested in the author and their content. They could subscribe to the author, receive updates, or even have articles sent directly to their email.

**Comment by Innei** [comment]
> an email subscription feature

Newsletters?

**Comment by runjuu** [comment]
@Innei Yes, but for the first version, if we don't have enough time, perhaps just an email update with a link to the article would suffice.

**Comment by birdgg** [comment]
> @Innei Yes, but for the first version, if we don't have enough time, perhaps just an email update with a link to the article would suffice.

Consider adding it after extracting the notification service.
