### ISSUE TITLE
[bug report] no publish button after editing xlog articles

### ISSUE THREAD

**Issue by cjh0613** [Crossbell-Box/xLog#721]
Mobile web page, no publish button after editing xlog articles

**Comment by DIYgod** [comment]
Thank you for the feedback, I have made the buttons of the mobile editor clearer. a102083a0460fcf2dc1786b1b761abeb2d0f2c91

<img width="390" alt="image" src="https://github.com/Crossbell-Box/xLog/assets/8266075/1e35f117-467e-4ea6-a5d7-08f8db85ad3b">

**Comment by DIYgod** [comment]
It's strange, I have already released the update. Could it be caused by your browser cache?
