### ISSUE TITLE
Will xlog provide the svg logo with text "xLog" ?

### ISSUE THREAD

**Issue by BEATING-HEART** [Crossbell-Box/xLog#740]

**Comment by BEATING-HEART** [comment]
![image](https://github.com/Crossbell-Box/xLog/assets/56473405/88e2e25e-855b-444c-a3c1-3b11830449ec)

**Comment by DIYgod** [comment]
There is currently no such SVG, but you can easily generate one using tools like Figma. May I ask what do you do with it?

**Comment by BEATING-HEART** [comment]
That's alright. Its not important. Just used as cover image, haha. Problem solved now. Thx.
BTW, although I could easily generate the logo myself, I highly recommend providing an official version.
