### ISSUE TITLE
[bug report] loading the text of an xLog article, it tends not to load the latest content, but rather the cached content

### ISSUE THREAD

**Issue by cjh0613** [Crossbell-Box/xLog#756]
En: 

When loading the text of an xLog article, it tends not to load the latest content, but rather the cached content. This is fine if the article is only viewed by visitors, but when the author edits the text, if it loads the previous content from the cache, it actually rolls back the last edited content.

----

Zh:

载入 xLog 的文本的时候，往往不会载入最新的内容，而会载入缓存的内容。如果只是访客进行浏览还好一些，但是作者编辑文本的时候，如果载入的是缓存的之前的内容的话，实际上会把上一次编辑的内容回滚。

**Comment by DIYgod** [comment]
Can you please explain in detail where the latest content cannot be loaded? Have you encountered old content loaded while editing?

**Comment by DIYgod** [comment]
There were indeed some unnecessary cache and it have been fixed in 2e6886ff85838be8091308edd9d040672083af9e, but I haven't encountered any cache issues with the editor. Can you confirm if the problem still exists now?
