### ISSUE TITLE
Obsidian plugin

### ISSUE THREAD

**Issue by DIYgod** [Crossbell-Box/xLog#766]

**Comment by DIYgod** [comment]
https://github.com/Crossbell-Box/xLog-Obsidian

**Comment by jokereven** [comment]
Does the obsidian plugin hope to publish articles to xlog through obsidian?

**Comment by DIYgod** [comment]
Yes, it should be able to sync and publish posts.

**Comment by DIYgod** [comment]
Now we have a good choice https://github.com/Otto-J/sync-to-xlog
