### ISSUE TITLE
Wallet cannot connect on mobile phone and iPad browser in xLog

### ISSUE THREAD

**Issue by Hsuey** [Crossbell-Box/xLog#778]
我在用手机浏览器和iPad浏览器无法连接xLog的Wallet
- 浏览器类型：手机（Free Adblocker Browser），iPad（Safari）
- 我的手机和iPad都安装了Coinbase Wallet app
- 钱包：Coinbase Wallet
- vpn节点：Hong Kong, Japan, US

出现情况：
- 点击连接钱包会出现图p2所示的二维码，但是很快就跳转到图p3，然后点击图p3中的Connect Coinbase Wallet，会跳转到Coinbase Wallet界面，如图p4所示，但是没有任何反应。
- 尝试过，当出现图p2页面的二维码时就停止网页加载，然后扫二维码登录，但是扫码后钱包没有任何反应，xlog.app网站刷新了一下关闭了二维码页面。
但是十多分钟过后手机的Coinbase Wallet才出现图p0所示的页面，手机端浏览器连接成功了，但是iPad连接不上 xLog 上的 Wallet

>图从左至右依次为：p0、p1、p2、p3、p4
<img src="https://user-images.githubusercontent.com/44939852/253429003-16ca0410-2848-49c1-bcff-ec2da2a1c3fc.png" alt="p0" width="15%"><img src="https://user-images.githubusercontent.com/44939852/253428831-12c558c9-3978-407b-9374-427cca0d2c1d.jpg" alt="P1" width="15%"><img src="https://user-images.githubusercontent.com/44939852/253428870-709bc77d-ab65-4c9b-aff8-f945a2c1fef9.jpg" alt="P2" width="15%"><img src="https://user-images.githubusercontent.com/44939852/253428915-7fcbc5cc-4079-4c85-b327-a1e27cc3c2d8.jpg" alt="p3" width="15%"><img src="https://user-images.githubusercontent.com/44939852/253428932-e1ea7dcf-6a41-4910-bcff-aa62b28a48e3.jpg" alt="p4" width="15%">
```
![p0](https://github.com/Crossbell-Box/xLog/assets/44939852/16ca0410-2848-49c1-bcff-ec2da2a1c3fc)
![P1](https://github.com/Crossbell-Box/xLog/assets/44939852/12c558c9-3978-407b-9374-427cca0d2c1d)
![P2](https://github.com/Crossbell-Box/xLog/assets/44939852/709bc77d-ab65-4c9b-aff8-f945a2c1fef9)
![p3](https://github.com/Crossbell-Box/xLog/assets/44939852/7fcbc5cc-4079-4c85-b327-a1e27cc3c2d8)
![p4](https://github.com/Crossbell-Box/xLog/assets/44939852/e1ea7dcf-6a41-4910-bcff-aa62b28a48e3)
```

**Comment by Hsuey** [comment]
Oh, I successfully connected in the xlog app https://oia.xlog.app/
But why is browsing xLog lagging on mobile phones or iPads compared to computers?

**Comment by DIYgod** [comment]
Fixed in #785
