### ISSUE TITLE
[bug report] Unable to open any of the article links on the xlog.app page

### ISSUE THREAD

**Issue by cjh0613** [Crossbell-Box/xLog#790]
Unable to open any of the article links on the https://xlog.app page:

`Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 1220422868`

**Comment by DIYgod** [comment]
I cannot reproduce it, but I suspect the issue may be related to CDN or some strange cache in your region.

**Comment by DIYgod** [comment]
I discovered a dependency bug, it has been fixed in 8c382bdbe38d60cd377f7e2a298f7cd53045671e. It is currently being released.
