### ISSUE TITLE
When I use pnpm dev to start the project locally, the avatar of the clicked person is wayner.undefined as username.undefined

### ISSUE THREAD

**Issue by jokereven** [Crossbell-Box/xLog#804]
![image](https://github.com/Crossbell-Box/xLog/assets/73232691/7bf45c6b-13ae-432e-9fdc-eb7bb57feebb)

**Comment by DIYgod** [comment]
According to [CONTRIBUTING.md](https://github.com/Crossbell-Box/xLog/blob/dev/CONTRIBUTING.md), you should copy `.env.example` to `.env`.

**Comment by jokereven** [comment]
The problem is solved, now is like http://wayner.localhost:2222 thanks.
