### ISSUE TITLE
 刚安装的测试模式，第一次登录要那个邮件收不到，垃圾邮箱里面也看了没有。 I just installed the test mode, but I couldn't receive the email I requested for the first login, and I didn't see it in the spam email.

### ISSUE THREAD

**Issue by aphantom** [Crossbell-Box/xLog#847]
![image](https://github.com/Crossbell-Box/xLog/assets/16313864/51d35f81-c1bd-4835-95a8-f302d640b7a6)

**Comment by DIYgod** [comment]
What is test mode?

**Comment by aphantom** [comment]
develop

**Comment by DIYgod** [comment]
How did you install it? Did you follow the instructions in CONTRIBUTING.md?

**Comment by aphantom** [comment]
Yes, I followed the steps in CONTABUTING.md to install, and the installation was also very smooth. It should be noted that I did not use a Docker container.

**Comment by aphantom** [comment]
![1690936857064](https://github.com/Crossbell-Box/xLog/assets/16313864/ca37b1d3-a723-40b6-9c9a-ef7d5d8b6254)
Entered email, but did not receive activation email

**Comment by aphantom** [comment]
pnpm dev

> proselog@ dev E:\use\xLog_Z
> next

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from E:\use\xLog_Z\.env
wait  - compiling...
event - compiled client and server successfully in 3.5s (299 modules)
warn  - using beta Middleware (not covered by semver) - https://nextjs.org/docs/messages/beta-middleware
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
wait  - compiling /_middleware...
wait  - compiling...
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
event - compiled client and server successfully in 15.7s (348 modules)
GET /
GET /
wait  - compiling / (client and server)...
wait  - compiling...
event - compiled client and server successfully in 706 ms (400 modules)
connecting to postgres://postgres:Wgij2273@localhost:5432/postgres?schema=public
connecting to postgres://postgres:Wgij2273@localhost:5432/postgres?schema=public
GET /favicon.ico
wait  - compiling /_error (client and server)...
wait  - compiling...
event - compiled client and server successfully in 155 ms (401 modules)
POST /api/trpc/auth.requestLoginLink?batch=1
wait  - compiling /api/trpc/[trpc]...
wait  - compiling...
event - compiled client and server successfully in 682 ms (460 modules)
prisma:info Starting a postgresql pool with 9 connections.
prisma:query BEGIN
prisma:query INSERT INTO "public"."login_tokens" ("id","email","expiresAt") VALUES ($1,$2,$3) RETURNING "public"."login_tokens"."id"
prisma:query SELECT "public"."login_tokens"."id", "public"."login_tokens"."email", "public"."login_tokens"."expiresAt", "public"."login_tokens"."subscribeForm" FROM "public"."login_tokens" WHERE "public"."login_tokens"."id" = $1 LIMIT $2 OFFSET $3
prisma:query COMMIT
query took 1233 ms
{
  from: 'Proselog <hi@proselog.com>',
  to: 'xtaww@163.com',
  subject: 'Sign in to Proselog',
  html: '\n' +
    '  <p>Hello,</p>\n' +
    '\n' +
    '  <p>We received a request to sign in to Proselog using this email address, please click the link below to sign in:</p>\n' +
    '\n' +
    '  <a href="http://localhost:3000/api/login?token=89b92706-c3f8-45e5-adc9-0e79e4e6722f&next=http%3A%2F%2Flocalhost%3A3000%2F">Sign in to Proselog</a>\n' +
    '  \n' +
    '  <p>This link will expire in 10 minutes. If you did not request this link, you can safely ignore this email.</p>\n' +
    '  \n' +
    '  <p>Thanks,</p>\n' +
    '\n' +
    '  <p>Your Proselog Team</p>\n' +
    '  '
}
not sending email because no mailgun apikey or domain configured

**Comment by DIYgod** [comment]
From the screenshot, I think you are using this project: https://github.com/proselog/proselog instead of this project.

**Comment by aphantom** [comment]
Think you! Is done.
