### ISSUE TITLE
[Suggestions] Do xLog consider introducing "Column" feature?

### ISSUE THREAD

**Issue by sora-blue** [Crossbell-Box/xLog#848]
Like if you write different posts on various topics, these posts can be put into different columns, and when readers click on one column, all posts of one topic can be found, instead of massive posts of colorful topics pop out in one screen when you visit one's main page. On top of it, there can be one rss for each column. Though there's already feature called "tag", the two can be completely different things.

**Comment by DIYgod** [comment]
I don't understand how it differs from the `tag`.

**Comment by sora-blue** [comment]
"tag" connects loose set of posts that is linked together by one single common point, e.g. that they are posted in the same year, or that they are all about traveling. 
"column" implies that the posts are highly related to each other by multiple points, e.g. that they are a series of network insights, or that they are about a 7-day trip to Ireland / another trip to New Zealand, etc.
Well, it's just a trivial suggestion. Maybe it really makes no sense.

**Comment by DIYgod** [comment]
I understand, it seems to be a stronger tag, but I think there is no problem using the regular tags. You can set up a series of posts with the same tag and then use the tag page to list these posts.
