### ISSUE TITLE
我似乎有一个旧的自己关注了自己，并且无法取消。

### ISSUE THREAD

**Issue by ethan-ih** [Crossbell-Box/xLog#856]
<img width="440" alt="CleanShot 2023-08-02 at 03 08 55@2x" src="https://github.com/Crossbell-Box/xLog/assets/105411793/0fabefb7-d397-44c9-a23b-41a7de972338">

我之前的一个 character 好像关注了自己，然而这个 character 现已被我删除了，所以有一些苦恼，希望可以修复这部分的 Bug.

**Comment by DIYgod** [comment]
Is this the address: https://www.ethanblog.cn/ ? It looks like this on my end, and I haven't encountered this problem.

<img width="448" alt="image" src="https://github.com/Crossbell-Box/xLog/assets/8266075/9afa03e3-5ce8-4f75-992f-2a9479f13276">
