### ISSUE TITLE
[Feature Request] Add markdown built-in components 

### ISSUE THREAD

**Issue by zhuozhiyongde** [Crossbell-Box/xLog#857]
I hope xLog can provide support similar to Docus' `<Alert />` and `<Badge />`.

Link: [Docus.dev](https://docus.dev/api/components)

![Cleanshot-2023-08-02-at-03 47 38](https://github.com/Crossbell-Box/xLog/assets/36695271/f6d487e0-a153-418e-bcf5-afa97df8a2e1)

It seems simple, and it can even be implemented using existing HTML syntax. However, I still prefer to have official support because I think alerts are quite commonly used.

**Comment by DIYgod** [comment]
Certainly, we can refer to the implementation of GitHub, like this:

> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

**Comment by zhuozhiyongde** [comment]
Oh, this seems to be exactly what I want, but it doesn't seem to be in the official manuals of [GFM](https://github.github.com/gfm) and [xFM](https://xlog.xlog.app/xfm). I wonder if you could add it.
