### ISSUE TITLE
[Feature Request] Support for custom link jump mapping

### ISSUE THREAD

**Issue by zhuozhiyongde** [Crossbell-Box/xLog#858]
I am migrating from WordPress to xLog, and I hope to keep the original links mapped to the new blog address. However, the original links may have path parameters like `https://xxx.com/?p=123`, while xLog now only provides direct and single link addresses like `https://xxx.com/123`. If possible, I would like to set up similar redirection in xLog.

**Comment by DIYgod** [comment]
It is difficult to do such custom redirection in the project. But if you are using Cloudflare, you can easily achieve this kind of redirection by using its page rules.

**Comment by zhuozhiyongde** [comment]
Thank you for your reply! Unfortunately, I can't use Cloudflare to host my domain name. If xLog doesn't provide built-in support for redirection, I think I'll have to give up the previous link.
