### ISSUE TITLE
[Bug Report] Display error of transparent background SVG/PNG images.

### ISSUE THREAD

**Issue by zhuozhiyongde** [Crossbell-Box/xLog#859]
On the homepage, all images of each article will be displayed in a carousel. This is good, but when the image is an SVG or transparent PNG image, the new image will **overlap** on top of the previous one, causing incorrect display. By searching through the code, I found that this seems to be an issue with the `Swiper` library and I'm not sure if it can be resolved.

![Cleanshot-2023-08-02-at-04 01 19](https://github.com/Crossbell-Box/xLog/assets/36695271/21f15c20-5290-4704-a30d-2938fc4ea75c)

Link: [Homepage](https://xlog.app/site/arthals)

By the way, there is another small display issue. The Github icon does not stand out when dark mode is enabled. I think we can refer to the icon operation on the official Github website and make a modification: in dark mode, replace it with a white background logo or use CSS filter.

Current (xLog):
![Cleanshot-2023-08-02-at-04 02 30](https://github.com/Crossbell-Box/xLog/assets/36695271/8113aa50-c6d1-4029-ae2a-03a8985e4feb)

Github Official Website:

Light mode:
![Cleanshot-2023-08-02-at-04 03 17](https://github.com/Crossbell-Box/xLog/assets/36695271/f1120086-a5c3-436e-98dc-f26b2f751e23)

Dark mode:
![Cleanshot-2023-08-02-at-04 04 20](https://github.com/Crossbell-Box/xLog/assets/36695271/b49f6eac-1fbf-4ff6-8811-6473b9633ad6)

> Forgive me for not being familiar with the React/Next.js framework and unable to directly modify the source code and submit a PR. I can only offer a few suggestions as a beginner. Sorry :)

**Comment by DIYgod** [comment]
Thank you for your feedback. I will handle it soon.

**Comment by zhuozhiyongde** [comment]
Thanks!

**Comment by DIYgod** [comment]
The first issue of transparent image display has been fixed in 4dcafb9ff624d851eb6d4fb7e7b1110f91494a0c

**Comment by DIYgod** [comment]
The dark mode github logo has been fixed in f822b299150c268c60bd2225010f8a4b2eebf59f

**Comment by zhuozhiyongde** [comment]
Thanks!
