### ISSUE TITLE
【Bug Report】: Incorrect NFT Display on /nft Page

### ISSUE THREAD

**Issue by lesenelir** [Crossbell-Box/xLog#867]
### Description:

I've encountered a display issue on the `/nft` page in the production version. Specifically, some NFTs are not being displayed correctly.

https://lesenelir.xlog.app/nft

<img width="1038" alt="Screenshot 2023-08-04 at 18 07 14" src="https://github.com/Crossbell-Box/xLog/assets/47740312/57b9baab-1f4c-44fd-939d-f7097b430b18">

### Detailed Findings:

Upon diving deeper into the issue in development mode, I pinpointed that the `content_uri` of the problematic NFTs starts with `<svg>`. Our current implementation appears to treat SVG data as if it were an IPFS link. As a result, when `nft.content_uri` contains SVG data instead of an actual IPFS link, the `toGateway` function is misreading this SVG data as an IPFS path, leading to errors.

<img width="1519" alt="Screenshot 2023-08-05 at 16 37 02" src="https://github.com/Crossbell-Box/xLog/assets/47740312/2ab53936-801f-44de-b04f-f449ae8c0330">

I will submit a PR to solve this issue later.

### PS
Separately, I've come across another issue during the setup. Despite closely following the documentation and copying `.env.example` to `.env`, post-execution, I'm experiencing a TypeError: fetch failed, and many images aren't loading correctly. Any insights on this would be appreciated.

<img width="1782" alt="Screenshot 2023-08-05 at 18 20 54" src="https://github.com/Crossbell-Box/xLog/assets/47740312/ce40db41-d269-4ee4-8d7f-4040b7af9073">

**Comment by lesenelir** [comment]
https://github.com/Crossbell-Box/xLog/pull/868

**Comment by DIYgod** [comment]
I don't know the reason either. Can you check which request failed?

**Comment by lesenelir** [comment]
Hello, I have figured out why my image requests all failed. It was a problem with my network ...

Reconfiguring the network proxy for docker can solve this problem!

Thank you ~
