### ISSUE TITLE
[feature request] hope the built-in Bilibili player can support video collection links

### ISSUE THREAD

**Issue by BEATING-HEART** [Crossbell-Box/xLog#883]
for example, this link cannot be parsed.
https://www.bilibili.com/video/BV1JV411t7ow/

This link is actually a collection of videos.
![image](https://github.com/Crossbell-Box/xLog/assets/56473405/37438958-41cc-444f-a5d4-29fc6cfdf609)

https://www.bilibili.com/video/BV1JV411t7ow/?p=3/  also failed. I seems that we cannot select a vedio from collection links.

**Comment by jokereven** [comment]
> for example, this link cannot be parsed. https://www.bilibili.com/video/BV1JV411t7ow/
> 
> This link is actually a collection of videos. ![image](https://user-images.githubusercontent.com/56473405/259292606-37438958-41cc-444f-a5d4-29fc6cfdf609.png)
> 
> https://www.bilibili.com/video/BV1JV411t7ow/?p=3/ also failed. I seems that we cannot select a vedio from collection links.

do you mean that? 
![image](https://github.com/Crossbell-Box/xLog/assets/73232691/3fb8164e-8bb5-4edc-bcc5-1b2be70b4242)

the base link have parsed successfully, but the end link have parsed failure, it have parsed like the first link, i think that is the network problem, the second question is dose exist;

![image](https://github.com/Crossbell-Box/xLog/assets/73232691/3a642e45-9622-4426-bd51-bbce6cc437e4)

when i use the official link to parsed it's also no use;

**Comment by DIYgod** [comment]
This embedded player is provided by bilibili official, and we do not have permission to modify it.
