### ISSUE TITLE
why? Your current $CSB balance is not enough to send this transaction. Please transfer to your operator.

### ISSUE THREAD

**Issue by andrewji8** [Crossbell-Box/xLog#931]
Your current $CSB balance is not enough to send this transaction. Please transfer to your operator.
![Screenshot_3](https://github.com/Crossbell-Box/xLog/assets/102641904/e2cd3c73-3693-4d36-8599-5344d644599e)
![Screenshot_4](https://github.com/Crossbell-Box/xLog/assets/102641904/24e09027-1e3c-4eb1-915b-60ade959b52c)

**Comment by DIYgod** [comment]
This is because the account balance of op sign is separate. 

@runjuu perhaps we should consider using a clearer prompt.

**Comment by runjuu** [comment]
Definitely! How about we change it to:

> Your current $CSB balance of [Operator Sign](https://crossbell-io-updates.xlog.app/Weekly-Updates-2023%2F02%2F06#operator-sign) is not enough to send this transaction. Please transfer more to your operator.

Does that sound better?

**Comment by DIYgod** [comment]
> Definitely! How about we change it to:
> 
> > Your current $CSB balance of [Operator Sign](https://crossbell-io-updates.xlog.app/Weekly-Updates-2023%2F02%2F06#operator-sign) is not enough to send this transaction. Please transfer more to your operator.
> 
> Does that sound better?

That definitely sounds better!
