### ISSUE TITLE
Bug: When opening a new xlog page, there may be a 404 request that needs to be refreshed manually;

### ISSUE THREAD

**Issue by jokereven** [Crossbell-Box/xLog#938]
![image](https://github.com/Crossbell-Box/xLog/assets/73232691/1a8a05f1-83b8-47e7-914c-2b9eb0546fe3)

**Comment by DIYgod** [comment]
Unable to reproduce, may be caused by network jam.

**Comment by jokereven** [comment]
but before never happen

**Comment by DIYgod** [comment]
Can you reproduce this issue?

**Comment by jokereven** [comment]
i have try open ten page but not reproduce, maby is network problem.
