### ISSUE TITLE
[Bug] Link to commented comment in dashboard/comments redirected to homepage of diygod.cc

### ISSUE THREAD

**Issue by carica** [Crossbell-Box/xLog#960]
What's the intended behavior tho?

**Comment by DIYgod** [comment]
Can you explain which specific comment it is? It would be best if you could provide a screenshot.

**Comment by carica** [comment]
> Can you explain which specific comment it is? It would be best if you could provide a screenshot.

sure. https://xlog.app/api/redirection?characterId=51470&noteId=226
![image](https://github.com/Crossbell-Box/xLog/assets/4182063/ad2b543a-f9b2-423b-b37c-ff7361480db0)
I was not sure if the comment above was linked to diygod.cc as intended.

**Comment by jokereven** [comment]
> > Can you explain which specific comment it is? It would be best if you could provide a screenshot.
> 
> sure. https://xlog.app/api/redirection?characterId=51470&noteId=226 ![image](https://user-images.githubusercontent.com/4182063/266350448-ad2b543a-f9b2-423b-b37c-ff7361480db0.png) I was not sure if the comment above was linked to diygod.cc as intended.

i saw that in https://xfeed.app/notes/51470-226, but no commit in https://log.cosmiccliffs.cc/fcitx-rime-pei-zhi-wu-song-pin-yin

**Comment by carica** [comment]
> > > Can you explain which specific comment it is? It would be best if you could provide a screenshot.
> > 
> > 
> > sure. https://xlog.app/api/redirection?characterId=51470&noteId=226 ![image](https://user-images.githubusercontent.com/4182063/266350448-ad2b543a-f9b2-423b-b37c-ff7361480db0.png) I was not sure if the comment above was linked to diygod.cc as intended.
> 
> i saw that in https://xfeed.app/notes/51470-226, but no commit in https://log.cosmiccliffs.cc/fcitx-rime-pei-zhi-wu-song-pin-yin

I don't consider https://log.cosmiccliffs.cc/fcitx-rime-pei-zhi-wu-song-pin-yin to be the correct post. https://xfeed.app/notes/51470-226 was a comment on https://dvel.me/posts/rime-ice/

**Comment by DIYgod** [comment]
这是由于考虑到查询性能，xLog 目前只支持了三级回复，再下一级的回复会无法查询到

<img width="834" alt="image" src="https://github.com/Crossbell-Box/xLog/assets/8266075/c26071c1-3ca8-4f1d-a603-8449681a4944">
