### ISSUE TITLE
Language switch not working in custom domain site

### ISSUE THREAD

**Issue by hyoban** [Crossbell-Box/xLog#973]
Maybe we shouldn't limit the `preferred_language` cookie to our domain, but I don't know if there are other considerations in this matter.

https://github.com/Crossbell-Box/xLog/blob/dev/src/lib/i18n/client.ts#L55C40-L55C62

**Comment by DIYgod** [comment]
Cookies by default can only be accessed by the current domain. Adding OUR_DOMAIN allows subdomains to also access it. As for custom domains, they are not possible to access.
