### ISSUE TITLE
能否提供一个选项允许将上传前的图片压缩到实际显示的大小

### ISSUE THREAD

**Issue by 89ao** [Crossbell-Box/xLog#986]
当前文章的封面图，如果传了高画质图片，那么在页面加载的时候会因为图片过大加载速度变慢。
用户自行压缩会相对麻烦一点，能否提供一个能力在上传的时候按实际显示大小压缩或者裁切？

**Comment by DIYgod** [comment]
We have added image compression when displaying pictures. If you still feel it is slow, please provide the specific image so that we can take a closer look.

**Comment by 89ao** [comment]
@DIYgod  thanks a lot ,quick response.
